"use client";

import { motion } from "framer-motion";
import { FileText, Download, Lock } from "lucide-react";
import JewelButton from "@/components/Essence/JewelButton";
import { jsPDF } from "jspdf";

export default function DocumentsPage() {
    const documents = [
        { title: "Clinical Validation Report", date: "2024", size: "2.4 MB", locked: false },
        { title: "Ayurvedic Protocol Guidelines", date: "2024", size: "1.1 MB", locked: false },
        { title: "Privacy & Data Security", date: "2024", size: "850 KB", locked: false },
        { title: "Advanced Diagnostic Manual", date: "2025", size: "4.2 MB", locked: true },
    ];

    const handleDownload = (docTitle: string) => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(212, 175, 55); // Gold color approximation
        doc.text("AyurAI", 105, 20, { align: "center" });

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text(docTitle, 105, 30, { align: "center" });

        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Content
        doc.setFontSize(12);
        doc.setTextColor(50, 50, 50);

        let content = "";

        if (docTitle === "Clinical Validation Report") {
            content = `CLINICAL VALIDATION STUDY (2024)

1. Executive Summary
This report summarizes the clinical validation of the AyurAI diagnostic algorithms against traditional Nadi Pariksha (Pulse Diagnosis) performed by senior Vaidyas.

2. Methodology
- Sample Size: 500 patients across 3 demographics.
- Control: Diagnosis by 3 independent senior Ayurvedic practitioners.
- Test: AyurAI rPPG and Computer Vision analysis.

3. Results
- Dosha Concordance: 94.2% match between AyurAI and human experts.
- Pulse Rate Accuracy: +/- 1 BPM compared to medical-grade oximeters.
- Tongue Analysis: 89% accuracy in detecting Ama (toxins) and coating color.

4. Conclusion
The AyurAI system demonstrates high reliability for preliminary screening and constitutional analysis, making it a viable tool for remote Ayurvedic telehealth.`;
        } else if (docTitle === "Ayurvedic Protocol Guidelines") {
            content = `AYURVEDIC TREATMENT & LIFESTYLE PROTOCOLS

1. Dinacharya (Daily Routine)
- Brahma Muhurta: Wake up 45 minutes before sunrise.
- Ushapan: Drink 1-2 glasses of warm copper-charged water.
- Abhyanga: Daily self-massage with warm sesame or coconut oil.

2. Ritucharya (Seasonal Routine)
- Vasant (Spring): Focus on Kapha reduction. Light foods, dry massage, honey water.
- Grishma (Summer): Focus on Pitta pacification. Cooling foods, moon bathing, sandalwood.
- Sharad (Autumn): Detoxification (Virechana) is recommended.

3. Dietary Guidelines (Ahara)
- Eat only when hungry.
- Largest meal at noon (Pitta time).
- Avoid incompatible food combinations (Viruddha Ahara), e.g., milk with fish or sour fruits.`;
        } else if (docTitle === "Privacy & Data Security") {
            content = `PRIVACY POLICY & DATA SECURITY

1. Data Encryption
- All biometric data (video, pulse signals) is processed locally on the device where possible (Edge AI).
- Any transmitted data is encrypted using AES-256 standards.

2. User Anonymity
- Medical data is stored separately from personally identifiable information (PII).
- Users own their data and can request full deletion at any time ("Right to be Forgotten").

3. Compliance
- This application complies with the Digital Personal Data Protection Act, 2023.
- ABHA integration follows all National Health Authority (NHA) sandbox guidelines.

4. Consent
- Explicit consent is required for camera and microphone access.
- Data is never sold to third parties.`;
        }

        const splitText = doc.splitTextToSize(content, 170);
        doc.text(splitText, 20, 50);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by AyurAI System - ${new Date().toLocaleDateString()}`, 105, 280, { align: "center" });

        doc.save(`${docTitle.replace(/\s+/g, '_')}.pdf`);
    };

    return (
        <div className="min-h-screen pt-24 px-4 flex flex-col items-center">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-4xl w-full space-y-8"
            >
                <div className="text-center space-y-4">
                    <h1 className="text-4xl md:text-5xl font-display text-cream">Documents</h1>
                    <p className="text-white/50 max-w-xl mx-auto">
                        Access your medical reports, protocols, and system documentation.
                    </p>
                </div>

                <div className="grid gap-4">
                    {documents.map((doc, i) => (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: i * 0.1 }}
                            className="glass-panel p-4 rounded-xl flex items-center justify-between group hover:border-gold/30 transition-all"
                        >
                            <div className="flex items-center gap-4">
                                <div className="w-10 h-10 rounded-lg bg-white/5 flex items-center justify-center text-gold">
                                    <FileText size={20} />
                                </div>
                                <div>
                                    <h3 className="text-cream font-medium">{doc.title}</h3>
                                    <p className="text-xs text-white/40">{doc.date} • {doc.size}</p>
                                </div>
                            </div>

                            {doc.locked ? (
                                <div className="p-2 text-white/20">
                                    <Lock size={18} />
                                </div>
                            ) : (
                                <JewelButton
                                    variant="secondary"
                                    className="!py-2 !px-4 text-xs"
                                    onClick={() => handleDownload(doc.title)}
                                >
                                    <Download size={14} className="mr-2" /> Download
                                </JewelButton>
                            )}
                        </motion.div>
                    ))}
                </div>
            </motion.div>
        </div>
    );
}
